theme: jekyll-theme-minimal
title: Microbial marker gene reference database for wastewater
description: Full-length 16S rRNA gene sequences from a diverse sample set of untreated wastewater
markdown: kramdown
logo: methods.png
